language: elixir
elixir:
  - 1.6.0
otp_release:
  - 19.3
  - 20.0
cache:
  directories:
    - _build
    - deps
    - node_modules
    - $MIX_HOME
services:
  - docker
before_install:
  - npm install
  - docker pull swaggerapi/swagger-codegen-cli
script:
  - scripts/ci.sh
